'use client'

import Link from 'next/link'
import { useState } from 'react'
import { Award, CalendarCheck, ChevronLeft, Clock3, Medal, Plus, Trophy, Users } from 'lucide-react'
import { Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { attentionStudents, activities, beltData, progressData, quickActions, upcomingEvents } from '@/lib/razmyar-dashboard-data'

const kpis = [
  ['شاگردان فعال', '۳۲', '۳ نفر بیشتر از ماه گذشته', Users], ['میانگین حضور', '۸۷٪', '۴٪ بیشتر از ماه گذشته', CalendarCheck], ['آماده ارتقا', '۷ نفر', 'نیازمند ارزیابی نهایی', Medal], ['مسابقات پیش رو', '۳', 'در ۳۰ روز آینده', Trophy],
]
const beltColors = ['#e2e8f0', '#eab308', '#22c55e', '#3b82f6', '#ef4444', '#111827']

function SectionTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: string }) {
  return <div className="mb-5 flex items-start justify-between gap-3"><div><h2 className="font-bold">{title}</h2>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action && <Link href="/reports" className="text-xs text-primary hover:underline">{action}</Link>}</div>
}

export function CoachDashboard() {
  const [range, setRange] = useState('این ماه')
  return <div className="mx-auto flex max-w-7xl flex-col gap-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs text-muted-foreground">جمعه، ۱۴ شهریور ۱۴۰۵</p><h2 className="text-2xl font-bold">داشبورد</h2><p className="mt-2 text-sm text-muted-foreground">نمای کلی وضعیت باشگاه و شاگردان شما</p></div><Link href="/students" className="flex w-fit items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="size-4" />افزودن شاگرد</Link></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{kpis.map(([label, value, hint, Icon]) => <section key={label as string} className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="flex items-center justify-between gap-2"><p className="text-xs text-muted-foreground">{label as string}</p><span className="rounded-lg bg-accent p-2 text-primary"><Icon className="size-4" /></span></div><p className="mt-4 text-xl font-bold md:text-2xl">{value as string}</p><p className="mt-2 text-[10px] text-primary md:text-xs">{hint as string}</p></section>)}</div>
    <div className="grid gap-6 lg:grid-cols-[1.15fr_1fr]">
      <section className="rounded-2xl border border-border bg-card p-5"><SectionTitle title="نیازمند توجه" subtitle="شاگردانی که بهتر است امروز بررسی شوند" /> <div className="flex flex-col gap-2">{attentionStudents.map(s => <Link href={`/students/${s.id}`} key={s.id} className="flex items-center gap-3 rounded-xl p-2.5 hover:bg-muted"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-accent text-sm font-bold text-primary">{s.name[0]}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{s.name}</span><span className="block truncate text-xs text-muted-foreground">کمربند {s.belt} · {s.issue}</span></span><span className="text-left"><span className="block text-xs font-semibold text-amber-400">{s.status}</span><span className="block text-xs text-muted-foreground">{s.metric}</span></span><ChevronLeft className="size-4 text-muted-foreground" /></Link>)}</div></section>
      <section className="rounded-2xl border border-border bg-card p-5"><SectionTitle title="روند پیشرفت شاگردان" subtitle="میانگین امتیاز مهارتی در طول زمان" /><div className="mb-3 flex gap-1 rounded-lg bg-muted p-1">{['این هفته', 'این ماه', '۳ ماه اخیر'].map(item => <button key={item} onClick={() => setRange(item)} className={`flex-1 rounded-md px-2 py-1.5 text-[10px] ${range === item ? 'bg-card text-foreground shadow-sm' : 'text-muted-foreground'}`}>{item}</button>)}</div><div className="h-56"><ResponsiveContainer width="100%" height="100%"><LineChart data={progressData}><XAxis dataKey="name" tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><YAxis domain={[0, 100]} tick={{ fontSize: 10 }} axisLine={false} tickLine={false} /><Tooltip formatter={(value) => [`${value} امتیاز`, 'میانگین']} /><Line type="monotone" dataKey="value" stroke="var(--primary)" strokeWidth={3} dot={{ r: 4, fill: 'var(--primary)' }} /></LineChart></ResponsiveContainer></div></section>
    </div>
    <div className="grid gap-6 lg:grid-cols-[1fr_1.15fr]"><section className="rounded-2xl border border-border bg-card p-5"><SectionTitle title="توزیع کمربندها" /><div className="flex items-center gap-4"><div className="relative size-44 shrink-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={beltData} dataKey="value" nameKey="name" innerRadius={52} outerRadius={75} paddingAngle={3}>{beltData.map((_, i) => <Cell key={i} fill={beltColors[i]} stroke="none" />)}</Pie></PieChart></ResponsiveContainer><div className="absolute inset-0 flex flex-col items-center justify-center"><b className="text-xl">۳۲</b><span className="text-[10px] text-muted-foreground">شاگرد</span></div></div><div className="grid flex-1 grid-cols-2 gap-2 text-xs">{beltData.map((b, i) => <div key={b.name} className="flex items-center gap-2"><span className="size-2.5 rounded-full" style={{ backgroundColor: beltColors[i] }} /><span className="text-muted-foreground">{b.name}</span><b>{b.value}</b></div>)}</div></div></section><section className="rounded-2xl border border-border bg-card p-5"><SectionTitle title="رویدادهای پیش رو" action="مشاهده همه" /><div className="flex flex-col gap-3">{upcomingEvents.map(event => <div key={event.title} className="flex items-center gap-3 rounded-xl border border-border p-3"><span className="rounded-lg bg-accent p-2.5 text-primary"><Trophy className="size-5" /></span><div className="min-w-0 flex-1"><b className="block text-sm">{event.title}</b><span className="text-xs text-muted-foreground">{event.date} · {event.type}</span></div><span className="text-xs text-muted-foreground">{event.participants}</span></div>)}</div></section></div>
    <div className="grid gap-6 lg:grid-cols-[1fr_1fr]"><section className="rounded-2xl border border-border bg-card p-5"><SectionTitle title="فعالیت‌های اخیر" /><div className="flex flex-col gap-4">{activities.map(([text, time], i) => <div key={text} className="flex items-start gap-3"><span className="mt-0.5 rounded-full bg-accent p-2 text-primary"><Clock3 className="size-4" /></span><div><p className="text-sm">{text}</p><span className="text-xs text-muted-foreground">{time}</span></div>{i === 0 && <span className="mr-auto size-2 rounded-full bg-primary" />}</div>)}</div></section><section className="rounded-2xl border border-border bg-card p-5"><SectionTitle title="دسترسی سریع" /><div className="grid grid-cols-2 gap-3">{quickActions.map(action => <Link key={action.label} href={action.href} className="flex items-center gap-2 rounded-xl border border-border p-3 text-xs font-medium hover:border-primary/50 hover:bg-accent"><Award className="size-4 text-primary" />{action.label}</Link>)}</div></section></div>
  </div>
}
