export type Skill = { name: string; score: number; category: string }
export type StudentProfileData = { id: string; name: string; age: number; belt: string; className: string; studentNumber: string; mobile: string; joinedAt: string; experience: string; parent: string; parentMobile: string; attendance: number; medals: number; competitions: number; skills: Skill[] }
export const aliRezaei: StudentProfileData = { id: '1024', name: 'علی رضایی', age: 15, belt: 'آبی', className: 'نوجوانان', studentNumber: '۱۰۲۴', mobile: '۰۹۱۲۱۲۳۴۵۶۷', joinedAt: '۱۰ اردیبهشت ۱۴۰۳', experience: '۲ سال و ۴ ماه', parent: 'رضا رضایی', parentMobile: '۰۹۱۲۹۸۷۶۵۴۳', attendance: 87, medals: 3, competitions: 6, skills: [{ name: 'تکنیک‌های پا', score: 92, category: 'تکنیک' }, { name: 'سرعت اجرا', score: 88, category: 'تکنیک' }, { name: 'انعطاف‌پذیری', score: 91, category: 'آمادگی جسمانی' }, { name: 'حمله', score: 81, category: 'مبارزه' }, { name: 'دفاع', score: 64, category: 'مبارزه' }, { name: 'جابه‌جایی پا', score: 61, category: 'مبارزه' }, { name: 'حمله متقابل', score: 68, category: 'مبارزه' }, { name: 'فرم', score: 79, category: 'فرم' }] }
export const students = [aliRezaei, { ...aliRezaei, id: '1025', name: 'سارا کریمی', age: 14, belt: 'سبز', studentNumber: '۱۰۲۵', attendance: 93 }, { ...aliRezaei, id: '1026', name: 'محمد احمدی', age: 17, belt: 'قرمز', studentNumber: '۱۰۲۶', attendance: 81 }]
export const fa = (n: number) => n.toLocaleString('fa-IR')
export const months = ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور']
export const progress = months.map((name, i) => ({ name, value: [61, 64, 68, 71, 75, 78][i] }))
export const categoryScores = [{ name: 'تکنیک‌ها', value: 88 }, { name: 'فرم', value: 79 }, { name: 'مبارزه', value: 72 }, { name: 'آمادگی جسمانی', value: 91 }]
export const competitions = [{ name: 'جام تهران', place: 'مقام اول', medal: 'طلا', date: '۲۵ شهریور ۱۴۰۵' }, { name: 'مسابقات استان', place: 'مقام سوم', medal: 'برنز', date: '۱۰ مرداد ۱۴۰۵' }, { name: 'جام باشگاه‌ها', place: 'مقام دوم', medal: 'نقره', date: '۲۲ تیر ۱۴۰۵' }]
export const assessmentHistory = [{ title: 'ارزیابی تکنیک‌های پا', score: 92, date: '۱۲ شهریور ۱۴۰۵' }, { title: 'ارزیابی مبارزه', score: 72, date: '۵ شهریور ۱۴۰۵' }, { title: 'ارزیابی آمادگی جسمانی', score: 91, date: '۲۸ مرداد ۱۴۰۵' }]
export const beltRequirements = { تکنیک‌ها: 80, فرم: 80, مبارزه: 75, آمادگی_جسمانی: 70 }
